In [2]:
## 1. Tạo arr_zeros có 10 phần tử 0, phần tử thứ 5 = 1
import numpy as np
arr_zeros = np.zeros(10, dtype=int)
arr_zeros[4] = 1
print(arr_zeros)


[0 0 0 0 1 0 0 0 0 0]


In [3]:
## 2. arr_h từ 10 → 24, đảo ngược

arr_h = np.arange(10, 25)[::-1]
print(arr_h)


[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [4]:
## 3. Tạo arr_k và arr_i chỉ chứa phần tử khác 0

arr_k = np.array([1,2,0,8,2,0,1,3,0,5,0])
arr_i = arr_k[arr_k != 0]
print(arr_i)


[1 2 8 2 1 3 5]


In [5]:
## 4. Thêm 10 và 20 vào cuối arr_i

arr_i = np.append(arr_i, [10, 20])
print(arr_i)


[ 1  2  8  2  1  3  5 10 20]


In [6]:
## 5. arr_câu4, thay phần tử 100 đến 5

arr_i[arr_i == 100] = 5
print(arr_i)


[ 1  2  8  2  1  3  5 10 20]


In [7]:
## 6. Xóa phần tử vị trí index = 0,1,2

arr_i = np.delete(arr_i, [0,1,2])
print(arr_i)


[ 2  1  3  5 10 20]
